CREATE TABLE CHaMP_VisitFileFolders (FolderID INTEGER PRIMARY KEY NOT NULL, VisitID INTEGER NOT NULL REFERENCES CHaMP_Visits (VisitID) ON DELETE CASCADE, Name TEXT NOT NULL, URL TEXT NOT NULL, Description TEXT, IsField INTEGER NOT NULL DEFAULT (0), IsFile INTEGER NOT NULL DEFAULT (0));
UPDATE Metric_Definitions SET Description='Channel Unit Number within a site as identified during field data collection. 
;  5/11/17 CV update cm metric ID' WHERE MetricID=3262;
CREATE TABLE VersionDBColumns (ColumnID INTEGER PRIMARY KEY UNIQUE NOT NULL, TableID INTEGER REFERENCES VersionDBTables (TableID) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, ColumnName VARCHAR (50) NOT NULL, Description VARCHAR (1000), UpdatedOn DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP));
CREATE TABLE VersionDBTables (TableID INTEGER PRIMARY KEY NOT NULL, TableName VARCHAR (50) NOT NULL UNIQUE, Description VARCHAR (1000), UpdatedOn DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP));
UPDATE VersionInfo SET ValueInfo='50' WHERE rowid=3;
UPDATE VersionInfo SET ValueInfo='1 Dec 2017' WHERE rowid=4;
