INSERT INTO LookupListItems (ItemID, ListID, Title) VALUES (10200, 18, 'RUN_HYDROPREP');
UPDATE Metric_Definitions SET XPath = '/AuxMetrics/Metrics/VisitMetrics/BankfullLargeWoodVolumeInPools' WHERE MetricID = 4504;
DELETE FROM Metric_Plots;
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("1 Bankfull Width to Wetted Width", 139, 157, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("2 Integrated Wetted Width to Wetted Site Length", 35, 30, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("3 Integrated Bankfull Width to Bankfull Site Length", 37, 32, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("4 Average Bankfull Width to Integrated Bankfull Width", 139, 37, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("5 Average Wetted Width to Integrated Wetted Width", 35, 157, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("6 Wetted Area to Wetted Volume", 31, 34, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("7 Wetted Area to Bankfull Area", 31, 33, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("8 Wetted Volume to Bankfull Volume", 34, 45, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("9 Fast Turbulent Area to Fast Turbulent Volume", 14, 17, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("10 Fast Non Turbulent Area to Fast Turbulent Volume", 19, 22, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("11 Slow Water/Pool Area to Slow Water/Pool Volume", 9, 12, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("12 Bankfull Main Channel Width to Bankfull Side Channel Width", 3390, 3271, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("13 Wetted Main Channel Width to Wetted Side Channel Width", 3392, 3289, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("14 Gradient to Sinuosity", 25, 26, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("15 Residual Pool Depth to Wetted Site Length", 30, 3371, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("16 Thalweg Site Length to Wetted Site Length", 30, 27, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("17 Bankfull Area to Wetted Site Length", 30, 33, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("18 Wetted Area to Wetted Site Length", 30, 31, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("19 Bankfull Width to Average Depth Ratio to Gradient", 25, 151, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("20 Wetted Width to Average Depth Ratio to Gradient", 25, 169, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("21 Detrended Elevation SD to Gradient", 25, 36, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("22 Bankfull Depth to Wetted Site Length", 30, 3264, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("23 Thalweg Depth Avg to Wetted Site Length", 30, 3360, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("24 Alkalinity to Conductivity", 4494, 4493, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("25 D16 to D50", 4488, 4489, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("26 D50 to D84", 4489, 4490, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("27 Bankfull LW Volume to Wetted LW Volume", 4502, 4501, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("28 Bankfull LW Volume Fast-NT to Wetted LW Volume Fast-NT", 4692, 4507, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("29 Bankfull LW Volume SlowWater to Wetted LW Volume SlowWater", 4504, 4503, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("30 Bankfull LW Volume Fast-Turb to Wetted LW Volume Fast-Turb", 4693, 4505, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("31 Substrate >2mm to Substrate >6mm", 4491, 4492, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("32 D50 to Discharge", 4489, 4485, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("33 Discharge to Solar Summer Avg", 4485, 4518, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("34 Discharge to Drift Biomass", 4485, 4511, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("36 Undercut Area to Undercut Volume", 4517, 4513, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("35 Discharge to Riparian Cover Big Tree", 4485, 4495, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("36 Discharge to Riparian Canopy Cover Coniferous", 4485, 4496, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("37 Discharge to Riparian Ground Cover", 4485, 4497, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("38 Discharge to Non-Woody Cover", 4485, 4498, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("39 Discharge to Riparian Cover Understory", 4485, 4499, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("40 Discharge to No Riparian Understory Cover", 4485, 4540, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("41 Discharge to Riparian Cover Woody", 4485, 4500, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("42 Discharge to Avg Cobble Embeddedness", 4485, 4486, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("43 Discharge to Cobble Embeddedness SD", 4485, 4487, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("44 Fish Cover Total to Fish Cover Artificial", 4590, 4576, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("45 Fish Cover Total to Fish Cover LW", 4590, 4572, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("46 Fish Cover Total to Fish Cover None", 4590, 4577, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("47 Fish Cover Total to Fish Cover Terrestrial Veg", 4590, 4575, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("48 LW Frequency Wetted to LW Frequency Bankfull", 4574, 4578, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("49 Side Channel Area to Side Channel Pct", 4640, 4641, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("50 Boulders to Cobbles", 4588, 4589, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("51 Boulders to Coarse and Fine Gravel", 4588, 4571, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("52 Boulders to Sand and Fines", 4588, 4573, 10001);
INSERT INTO Metric_Plots (PlotTitle, XMetrixID, YMetricID, PlotTypeID) VALUES ("53 Pct Undercut (length) to Pct Undercut (area)", 4594, 4595, 10001);
UPDATE VersionInfo SET ValueInfo='49' WHERE rowid=3;
UPDATE VersionInfo SET ValueInfo='3 Nov 2017' WHERE rowid=4;
