INSERT INTO table VALUES(6,'John Day');
INSERT INTO table VALUES(11,'Umatilla');
INSERT INTO table VALUES(12,'Upper Grande Ronde');
INSERT INTO table VALUES(15,'Lolo Creek');
INSERT INTO table VALUES(16,'Tucannon');
INSERT INTO table VALUES(17,'Asotin');
INSERT INTO table VALUES(18,'South Fork Salmon');
INSERT INTO table VALUES(20,'Lemhi');
INSERT INTO table VALUES(23,'Wenatchee');
INSERT INTO table VALUES(24,'Entiat');
INSERT INTO table VALUES(25,'Methow ');
INSERT INTO table VALUES(27,'Big-Navarro-Garcia (CA)');
INSERT INTO table VALUES(29,'Region 17');
INSERT INTO table VALUES(30,'Yankee Fork');
INSERT INTO table VALUES(32,'Walla Walla');
INSERT INTO table VALUES(33,'Minam');
INSERT INTO table VALUES(99,'CHaMP Training');
INSERT INTO table VALUES(102,'Basinwide');
INSERT INTO table VALUES(104,'AEM Training');
