<?xml version="1.0" encoding="UTF8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:template match="surveyGDB">
    <html class="no-js" lang="en">
      <head> 
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Survey Editing Report</title>
        <xsl:call-template name="stylesheet" /> 
      </head>
      <body>
        <div class="container">
          <xsl:call-template name="header" /><!-- jumbotron -->

          <!--  Background --> 
          <h2>Background</h2>
          <p>Once a survey has been completed and imported from the instrument file into GIS, there are several critical steps in post-processing a survey that involve manual editing. This report provides descriptive information of the changes to the point cloud from which a surface was generated, the lines present in the survey, and changes to the TIN surface.</p> 

          <p>Since editing can be performed at different times during the point collection and post-processing workflow, these summaries are not an indicator of survey quality.</p>

          <!-- Point and Line Editing -->   
          <div class="panel panel-default"> 
            <div class="panel-heading"><div class="panel-title"><h2 class="top-pad">Point and line editing</h2></div></div>
            <div class="panel-body">
              <p>Crews have the opportunity to adjust points and lines during post processing. Adjustments may include adding and/or deleting points and line segments, changing description codes, or changing locational information.</p>
              <p>Before editing point counts are summarized from the Topo_Points featureclass after import. After editing point counts are summarized from the Topo_Points featureclass when the TIN is generated.</p>
              <p>According to the crew, the majority of the point edits occurred <span class="response"><xsl:value-of class="response" select="/surveyGDB/tables/table/records/record[QuestionID = 'TIN_01']/Response" /></span> and the majority of the edits to the breaklines (hard and soft) occurred <span class="response"><xsl:value-of select ="/surveyGDB/tables/table/records/record[QuestionID = 'TIN_02']/Response" /></span>.</p>
              <p>There <span class="response"><xsl:value-of select="/surveyGDB/tables/table/records/record[QuestionID = 'TIN_03']/Response" /></span> rod height busts in the original survey.</p>
              <p>Additional notes on rod heights: <span class="response"><xsl:value-of select="/surveyGDB/tables/table/records/record[QuestionID = 'TIN_03']/Notes" /></span></p>
              <h3 class="bottom-pad">Total Points: <span id="points-total" class="response"></span></h3>
            </div>
          </div>

          <!-- Point Editing Table -->
          <div class="metric">
            <h3 class="table-name">Point Editing Summary</h3>
            <table id="point-editing-summary" class="table">
              <thead>
                <tr>
                  <th>Code</th>
                  <th class="number-column">Point ct, before edits</th>
                  <th class="number-column">Point ct, after edits</th>
                  <th class="number-column">% Added</th>
                  <th class="number-column">% Deleted</th>
                  <th>Edited</th>
                  <th>Points Collected</th>
                </tr>
              </thead>                
              <tbody>
              </tbody>
            </table>
          </div>

          <!-- Line Editing Table -->
          <div class="metric">
            <h3 class="table-name">Line Editing Summary</h3>
            <table id="line-editing-summary" class="table">
              <thead>
                <tr>
                  <th>Code</th>
                  <th class="number-column">Line lgth (m), before edits</th>
                  <th class="number-column">Line lgth (m), after edits</th>
                  <th class="number-column">% Added</th>
                  <th class="number-column">% Deleted</th>
                  <th>Edited</th>
                  <th>Lines Collected</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>    


          <!-- TIN editing -->
          <div class="panel panel-default"> 
            <div class="panel-heading"><div class="panel-title"><h2>TIN Editing</h2></div></div>
            <div class="panel-body">
              <!-- variables derived from TIN summary table, using JS? -->
              <p>TINs are made of triangular facets that have nodes where the facet endpoints meet. These nodes can be generated from points collected by crews or artificial nodes that were generated by GIS during the TIN generation.</p>  
              <p>'<span id="final-tin" class="response">[0]</span>' is the final TIN and it was last processed on <span id="tin-last-timestamp" class="response">[LAST TIMESTAMP]</span> in <span id="tin-hours" class="response">[FIRST - LAST TIMESTAMP]</span>. According to the crew, the TIN was <span class="response"><xsl:value-of select ="/surveyGDB/tables/table/records/record[QuestionID = 'TIN_04']/Response" /></span> to edit. If TIN errors were present, repairs were made <span class="response"><xsl:value-of select ="/surveyGDB/tables/table/records/record[QuestionID = 'TIN_05']/Response" /></span>. The amount of editing done to the final TIN surface was <span class="response"><xsl:value-of select ="/surveyGDB/tables/table/records/record[QuestionID = 'TIN_07']/Response" /></span>. The following errors were found while editing and reviewing the TIN: <span class="response"><xsl:value-of select ="/surveyGDB/tables/table/records/record[QuestionID = 'TIN_06']/Response" /></span>. The crew considered the quality of the TIN produced as <span class="response"><xsl:value-of select ="/surveyGDB/tables/table/records/record[QuestionID = 'TIN_08']/Response" /></span>.</p>
              <p>In this survey, edits included the addition of <span id="nodes-added" class="response">[0]</span> nodes and deletion of <span id="nodes-deleted" class="response">[0]</span> nodes for a net change of <span id="nodes-delta" class="response">[0]</span>. <span id="nodes-topo" class="response">[0]</span> of the nodes originate from Topo Points. There are <span id="nodes-not-topo" class="response">[0]</span> topo points that are not nodes in the TIN. The survey includes <span id="bl-count" class="response">[0]</span> breakline(s). TIN editing changed the minimum node elevation by <span id="nodes-Zmax" class="response">[0]</span> and the maximum node elevation by <span id="nodes-Zmin" class="response">[0]</span>.</p>
              <p>There are <span id="bl-length" class="response">[0]</span> of breaklines that were used in the TIN generation and <span id="bl-cross" class="response">[0]</span> were crossed at the time of final TIN validation.</p>    
            </div>
            
            <!-- TIN node Editing summary table -->
            <div class="metric"> 
              <h3 class="table-name">TIN Node Editing Summary</h3>    
              <table id="node-editing-summary" class="table">
                <thead>
                  <tr>
                    <th>Code</th>
                    <th class="number-column">First TIN</th>
                    <th class="number-column">Last TIN</th>
                    <th class="number-column">% Addition</th>
                    <th class="number-column">% Deletion</th>
                  </tr>
                </thead>
                <tbody>
                </tbody>
              </table>
            </div>

            <!-- Image Snapshots -->
            <div class="panel panel-default"> 
              <h2>Review Images</h2>
            <!--  <xsl:variable name="mim-id" as="xs:string*" 
                select="'MIM_05', 'MIM_06', 'MIM_07', 'MIM_13'" /> -->
              <xsl:for-each select="/surveyGDB/tables/table[name='MapImages']/records/record[ImageCode='MIM_04' or ImageCode='MIM_05']" >
                <div class="panel-body">
                    <img src="{FilePath}" />
                    <p><xsl:value-of select="Title" /></p>
                </div>
              </xsl:for-each>
            </div>
              
            </div>
          </div>
          <xsl:call-template name="javascript" />
          <xsl:call-template name="JSON" />
        </body>
      </html>
    </xsl:template>

    <xsl:template name="header">
      <div class="jumbotron jumbo-blue">
        <div class="row">
          <div class="col-md-12">
            <h1>Survey Editing Report</h1>
            <h4>Created on: <xsl:value-of select="/surveyGDB/xmlcreated" /></h4>
            <div class="row">
              <div class="col-md-12">
                <h2 class="top-pad">Site Name: <xsl:value-of select="/surveyGDB/tables/table/records/record/SiteID" /></h2>
                <h2>Visit ID: <xsl:value-of select="/surveyGDB/tables/table/records/record/VisitID" /></h2>
                <ul class="list-unstyled">
                  <li>Watershed: <xsl:value-of select="/surveyGDB/tables/table/records/record/Watershed" /></li>
                  <li>Stream Name: <xsl:value-of select="/surveyGDB/tables/table/records/record/StreamName" /></li>
                  <li>Sampled: <xsl:value-of select="/surveyGDB/tables/table/records/record/SurveyDate" /></li>
                  <li>Survey GDB Name: <xsl:value-of select="/surveyGDB/filename" /></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6"><img class="img"></img></div> <!-- site map? -->
      </div> 
    </xsl:template>

    <xsl:template name="JSON">
     <script id="ReportJSONData" type="application/json"><xsl:value-of select="/surveyGDB/JSON"/></script>
   </xsl:template>

   <xsl:template name="javascript">
    <script src="tmp/editing_report.js?__inline=true"></script>
  </xsl:template>

  <xsl:template name="stylesheet">
    <link href="tmp/editing_report.css?__inline=true" rel="stylesheet" />
  </xsl:template>
</xsl:stylesheet>